FONPR Gym-type Environment Interface
DISHDevEx/fonpr pull request #12
Opened 2023-05-26 15:17 UTC by PaperArmada

This PR contributes a gymnasium type environment for interfacing Ray agents (or any other RL agent that leverages gymnasium) to interact with the Open5Gs ecosystem (at least the simple structure we have set up for our initial experiments).

2023-06-05 17:34 UTC, vinayakSharm reviewed
adding initial comments, since there has been a push to the files I will start another review

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/__init__.py
merge main (leaving comment for double check)

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/advisors/prometheus_client_advisor.py
good update

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/__init__.py
might want to put interface stuff into the rl_infrastructure folder

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +    ### Action Space
I love these comments. I will incorporate this level of clarity into DQN later

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +    def render(self):
I don't think we should have empty functions as part of the class.

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/utilities/prom_queries.py
> +def prom_query_rl_upf_experiment1():
can we rename this query to something more verbose.

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +        render():
can we remove if not implemented?

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +    def __init__(self, env_config={'render_mode':None, 'window':15, 'sample_rate':4, 'obs_period':5}) -> None:
why use a dictionary instead of raw variables here. Might be easier for a new user to setup an environment by passing in 4 variables instead of passing in 4 variables wrapped in a dictionary.

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +        self.window = env_config['window'] # How far back in time does the observation look, in minutes
it seems as though the window is static to 15 minutes because of the prometheus query

2023-06-05 17:34 UTC, vinayakSharm commented on fonpr/interfaces/fonpr_env.py
> +        self.window = env_config['window'] # How far back in time does the observation look, in minutes
changing window in the class does not change the prom query, is that functionality you would like?

2023-06-05 17:53 UTC, vinayakSharm requested changes
really small comments

2023-06-05 17:53 UTC, vinayakSharm commented on Dockerfile_SAC
nice!

2023-06-05 18:09 UTC, vinayakSharm requested changes

2023-06-05 18:52 UTC, PaperArmada commented on Dockerfile
Done

2023-06-05 19:54 UTC, PaperArmada commented on fonpr/interfaces/__init__.py
Updated to have a directory each for tf and ray; avoiding directory inits trying to pull packages for all agents.

2023-06-05 19:55 UTC, PaperArmada commented on fonpr/interfaces/fonpr_env.py
> +    ### Action Space
Nice

2023-06-05 19:56 UTC, PaperArmada commented on fonpr/interfaces/fonpr_env.py
> +    def render(self):
These are standard functions for Gymnasium type environments; understand the discomfort but will leave them in.

2023-06-05 20:02 UTC, PaperArmada commented on fonpr/utilities/prom_queries.py
> +def prom_query_rl_upf_experiment1():
Great thought; done

2023-06-05 20:13 UTC, PaperArmada commented on fonpr/rl_infrastructure/fonpr_env.py
> +        li_cost = ec2_cost_calculator(self.large_instance_type) # Cost of large instance in dollars per hour
Sure; updated to "large_cost" and "small_cost"

2023-06-05 20:33 UTC, PaperArmada commented on fonpr/rl_infrastructure/fonpr_env.py
> +    def __init__(self, env_config={'render_mode':None, 'window':15, 'sample_rate':4, 'obs_period':5}) -> None:
Updated comments. Main thing I'm trying to express there is that the constructor is flexible to desired sampling parameters, but we may not have control over the actual sample rate of Prometheus.

2023-06-05 20:36 UTC, PaperArmada commented on fonpr/rl_infrastructure/fonpr_env.py
done

2023-06-05 20:36 UTC, PaperArmada commented on fonpr/__init__.py
done

2023-06-05 20:37 UTC, PaperArmada commented on fonpr/__init__.py
done

2023-06-05 20:37 UTC, PaperArmada commented on fonpr/interfaces/fonpr_env.py
> +        render():
see earlier comment

2023-06-05 20:37 UTC, PaperArmada commented on fonpr/interfaces/fonpr_env.py
> +        self.window = env_config['window'] # How far back in time does the observation look, in minutes
Good catch; updated

2023-06-05 20:38 UTC, PaperArmada commented on Dockerfile_SAC
👍

2023-06-06 15:26 UTC, vinayakSharm requested changes
last minor changes needed to proceed

2023-06-06 15:26 UTC, vinayakSharm commented on fonpr/__init__.py
> +# from .tf_infrastructure import FonprDqn
need to uncomment these imports

2023-06-06 15:26 UTC, vinayakSharm commented on Dockerfile_SAC
> +COPY requirements.txt .
need to copy requirements_sac.txt

2023-06-06 15:26 UTC, vinayakSharm commented on Dockerfile_SAC
> +RUN pip install -r requirements.txt
need to install requirements_sac.txt

2023-06-06 15:26 UTC, vinayakSharm commented on fonpr/agent_sac.py
> +    s3_uri = 's3://respons-agent-checkpoints/sac_v0.0.0/'
name this variable to reflect that this is where the agent will checkpoint its params.

2023-06-06 20:23 UTC, vinayakSharm requested changes

2023-06-06 20:52 UTC, vinayakSharm commented
Hi Matt, I tried to compile the DQN but it seems its not possible with the current init file config

Traceback (most recent call last):
  File "/app/fonpr/agent_dqn.py", line 13, in <module>
    from tf_infrastructure import FonprDqn
  File "/app/fonpr/tf_infrastructure/__init__.py", line 5, in <module>
    from .driver import Driver
  File "/app/fonpr/tf_infrastructure/driver.py", line 7, in <module>
    from fonpr.action_handler.action_handler import ActionHandler, get_token
  File "/app/fonpr/__init__.py", line 19, in <module>
    from .ray_infrastructure import FONPR_Env
  File "/app/fonpr/ray_infrastructure/__init__.py", line 1, in <module>
    from .fonpr_env import FONPR_Env
  File "/app/fonpr/ray_infrastructure/fonpr_env.py", line 5, in <module>
    import gymnasium as gym
ModuleNotFoundError: No module named 'gymnasium'

Might have to find a way to fit the ray infra without breaking the imports for the DQN

2023-06-12 14:28 UTC, PaperArmada commented on fonpr/ray_infrastructure/fonpr_env.py
> +from advisors import PromClient
Were you seeing this breaking anywhere?

2023-06-12 14:41 UTC, PaperArmada commented on Dockerfile_SAC
> +COPY requirements.txt .
Good catch

2023-06-12 14:41 UTC, PaperArmada commented on Dockerfile_SAC
> +RUN pip install -r requirements.txt
Good catch

2023-06-14 18:57 UTC, vinayakSharm approved these changes

2023-06-14 19:10 UTC, merged