Transferring action handler logic.
DISHDevEx/fonpr pull request #5
Opened 2023-04-03 23:05 UTC by PaperArmada

Adding class to handle automated updates for helm value.yaml files on GitHub

2023-04-04 15:39 UTC, vinayakSharm commented
Initial Review: 
(1) Merge the latest copy of main into your working branch
(2) Move Advisor into the respons_ml
(3) Give instructions on how to run the newly added code
(4) Maybe add some stuff to talk about the spark advisor

2023-04-04 22:50 UTC, davidcherney commented on README.md
>  > This readme is devoted to aid deployment of agents that respond in real time to eks cluster settings:
Please clarify the nature of this list. 

Looks to me like it is a table of contents, but it follows a clause with a colon that does not indicate as much.

2023-04-04 23:07 UTC, davidcherney commented on README.md
>  1. Agent lives in the agent.py file.
The enumerations below are unmotivated. 

I suggest a description of the list be provided, or the enumeration removed to form a paragraph of sentences.

2023-04-04 23:09 UTC, davidcherney commented on README.md
>  1. There are 3 types of advisors at the agents desposal: prometheus, socket, spark.
Please beef #2 up into a sentence. 

Also, the word "current" is never a good idea in documentation.

2023-04-04 23:15 UTC, davidcherney commented on README.md
> +1. The ActionHandler class takes in a GitHub token, target file path within the repository, branch name, and agent-requested parameter update values.
At this point in the readme, what is more important that describing what the action handler takes in is describing what it is meant to do. 

The same goes for the other sections in the table of contents.

2023-04-06 14:50 UTC, davidcherney commented on README.md
> +docker pull -t imagename:version .
I think MSS should start developing a convention about how to present "you put a value here"

I have been using <> to denote places where the user is intended to modify input. 

e.g. `docker pull -t <image_name>:<version> .`

2023-04-07 21:10 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +
A sentence about FONPR/RESPONs and then some background/intro on how this fits in within would be very useful for the user.

2023-04-07 21:12 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +Account page -> Settings -> Developer settings -> Personal access tokens -> Fine-grained tokens
&rarr;

This code will show like the arrow above
\&rarr;

2023-04-07 21:13 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +* give it a name,
These seem like steps/directions so my recommendation would be to number them instead of bullets.

2023-04-07 21:15 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +```Python
As a user I found it hard to copy this into the terminal and then make changes. 
I think declaring the variables on their own line, and directing the user to copy line by line and edit would be clear and smoother.

Here's a suggestion on what I mean:

```
import action_handler
import os

requested_actions = {
    'target_pod' : 'amf',
    'requests' : {'memory' : 3, 'cpu' : 1},
    'limits' : {'memory' : 1, 'cpu' : 3}
}

token = os.environ['TOKEN']
filepath = 'DISHDevEx/openverso-charts/charts/respons/tomer_test_PR.txt'
repo_branch = 'matt/gh_api_test'
hndl = action_handler.ActionHandler(token, filepath, repo_branch, requested_actions)
hndl.establish_github_connection()
hndl.fetch_update_push()
```

2023-04-07 21:18 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +Attempting fetch of contents from test/test.txt:
Separate the output and introduce it as such. Something like:

Example of output:
```
Attempting fetch of contents from test/test.txt:
Fetch successful.
Updating YAML values:
Update complete.
Attempting push to test/test.txt:
Push complete.
```

2023-04-07 21:22 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +    ...
I thought this was the end of the docstring, so disregard my comment before about the double quotes. It was the sagemaker font's fault! 

Is this like a "..." indicating a continuation?

If you know this to be a standard, or you think it adds value, then I say leave as is.

2023-04-07 21:29 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +            session token that contains the appropriate GitHub credentials
I think your style and formatting looks great, but back when we started we agrees in sklearn style for docstrings, which is only a bit different. Empty row between 'Attributes' and call them 'Parameters' instead.

There's a good example here which i got from our confluence page.
https://gist.github.com/jakevdp/3808292

2023-04-07 21:33 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +        list_repos():
In sklean they put the whole method's docstring here ( help(LogisticRegression) has good examples of this). I feel like that's a bit overkill, but it's something we should discuss as a team next review/retro. Personally, I opted out to only put the description, and leave out 'Parameters' and 'Returns'.

2023-04-07 21:34 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +* give it a name,
An example with relevant name would help the user.

2023-04-07 21:34 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +* write reason for needing access,
What is a good example reason?

2023-04-07 21:36 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +* in Repository permissions, select 'Read and write' for Contents permissions,
I think it may read smoother if you add some quotation marks to named things.

in 'Repository permissions', select 'Read and write' for 'Contents' permissions

2023-04-07 21:49 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +            requested_actions = {
I believe there's an extra tab here.

2023-04-07 21:53 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +                target branch to pull from and push to (e.g. 'matt/gh_api_test')
Add requested_actions to this list too.

2023-04-07 21:59 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +            return yaml.dump(new_values)
I think you should assign this to a variable and return the variable. In the docstring you'll describe this variable under "Returns".

```
yaml_dump = yaml.dump(new_values)

"""
Update dictionary values with requested actions, and return in YAML file format.

Paramters
---------
    current_values : dict
        Description of this variable.

Returns
-------
    yaml_dump : YAML Object
        Description of this variable.
"""
```

2023-04-07 22:05 UTC, RemoNona commented on respons_ml/action_handler/action_handler.py
> +        get_value_file_contents must be called prior to use.
If were following sklearn I think it would look something this. If you agree then change the existing docstring to this style.
```
"""
Using connection to target repository, push the supplied updated file
back out to GitHub.

'get_value_file_contents' method must be called prior to use.

Paramters
---------
    updated_file : yaml.YAMLObject
        Description of this variable.
    
    message : str, default='auto-update'
        Description of this variable


Returns
-------
    None
"""
```

2023-04-07 22:07 UTC, RemoNona requested changes
Code works and looks great. Please see comments for minor formatting changes. Happy to discuss!

2023-04-10 16:32 UTC, vinayakSharm requested changes
(1) pls instantiate session inside of __init__ 

(2) pls update respons-ml/respons_ml/__init__.py  (the outer init file)

2023-04-10 16:32 UTC, vinayakSharm commented on README.md
> +## __4. Docker__
nice docker section

2023-04-10 16:32 UTC, vinayakSharm commented on respons_ml/action_handler/action_handler.py
> +        except Exception as excp:
love to see error handling. good

2023-04-10 16:32 UTC, vinayakSharm commented on respons_ml/action_handler/action_handler.py
> +    def establish_github_connection(self) -> None:
can you run this function as part of your init pls. And define self.session as part of your __init__ method as well. 

eg. 

    def __init__(self, 
        repo_token='', 
        value_file_path='', 
        branch_name='',
        requested_actions={}
        ):

               self.session = Github(self.repo_token) 
               ## OR self.session = self.establish_github_connection()




This is a pretty important attribute, pls also include it in the docstring. 

Having the self.session inside of the constructor will allow for ease of debugging, and will require less manual steps to set up an object of the class.

2023-04-10 16:32 UTC, vinayakSharm commented on respons_ml/action_handler/action_handler.py
> +def get_token(token_key='token'):
maybe run this function inside of the init as well? this suggestion only makes sense if every user of this class has to manually run this function post object declaration of class. 

If every time a user creates an object of the class, and it is mandatory for them to then run the get_token function, it may just make sense to automate this process by including a function call inside the init. 

If not, then pls disregard .

2023-04-10 17:30 UTC, PaperArmada commented on README.md
> +1. The ActionHandler class takes in a GitHub token, target file path within the repository, branch name, and agent-requested parameter update values.
Updated

2023-04-10 17:32 UTC, PaperArmada commented on README.md
> +docker pull -t imagename:version .
Updated

2023-04-10 17:54 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +
Updated

2023-04-10 17:57 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +Account page -> Settings -> Developer settings -> Personal access tokens -> Fine-grained tokens
For some reason &rarr was not rendering correctly in the md preview, but I did update arrows.

2023-04-10 17:59 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +* give it a name,
Updated

2023-04-10 18:03 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +```Python
Updated

2023-04-10 18:03 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +Attempting fetch of contents from test/test.txt:
Updated

2023-04-10 18:06 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +    ...
Should have been removed; thank you! Updated.

2023-04-10 18:24 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +        list_repos():
Copying description for custom methods into the class docstring; updated. Agreed on discussing with the team how we want to treat these details generally👍thanks!

2023-04-10 18:28 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +* write reason for needing access,
Updated

2023-04-10 18:29 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +* in Repository permissions, select 'Read and write' for Contents permissions,
Updated

2023-04-10 18:31 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +            requested_actions = {
Updated; please check that it meets your intent.

2023-04-10 18:34 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +                target branch to pull from and push to (e.g. 'matt/gh_api_test')
Updated

2023-04-10 18:39 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +            return yaml.dump(new_values)
Updated

2023-04-10 18:51 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +        get_value_file_contents must be called prior to use.
Updated

2023-04-10 19:16 UTC, PaperArmada commented on respons_ml/action_handler/action_handler.py
> +def get_token(token_key='token'):
Right now we've got a couple different ways to pass the token, so I'll leave it out for the time being, but noted and I agree that eventually having the process baked in would be preferable 👍

2023-04-11 16:35 UTC, RemoNona commented on respons_ml/action_handler/README.md
> +'target_pod' : 'amf',
Indent 46-48 for clearer formatting

2023-04-11 17:16 UTC, PaperArmada commented on respons_ml/action_handler/README.md
> +'target_pod' : 'amf',
Updated

2023-04-11 18:20 UTC, RemoNona approved these changes
Looks good! Thank you.

2023-04-11 22:41 UTC, merged