Matt/action handler integration
DISHDevEx/fonpr pull request #7
Opened 2023-04-13 20:24 UTC by PaperArmada

Integrating action handler into the agent execution flow.

2023-04-13 21:01 UTC, vinayakSharm requested changes
super minor edits. remove unused code snippits and functions. 

update code for pylint. 

will run code next. and provide feedback if code doesnt run thx

2023-04-17 16:34 UTC, PaperArmada commented on fonpr/agent.py
> +    parser.add_argument(
I wanted to build in the ability to update the Prometheus server endpoint at runtime, which this seems to do just fine, but it feels a little clunky to me. If there is a best practice here that I'm missing (or my mind is just running slow today and an obvious solution), please chime in.

2023-04-17 17:51 UTC, vinayakSharm commented
Can you please add to the macro read me how to change the file that the agent is updating on github. This should be part of the Action Handler section.

2023-04-17 18:09 UTC, vinayakSharm commented
Hi matt here are the steps I took to test your PR:

(1) I cloned your branch. 

(2) I then compiled the docker image locally from your branch

(3) pushed the docker image to dockerhub: teamrespons/respons_agent:matt.pr.test

(4) I then created a new manifest file: https://raw.githubusercontent.com/DISHDevEx/fonpr/vinny/action-handler-integration-pr/deployment/respons_agent_manifest.yml

(5) I deployed the agent to the EKS cluster

Here are my errors at step 5. The agent is deployed in the cluster but the logs say the following: 

'''
usage: FONPR_Agent [-h] I E
FONPR_Agent: error: the following arguments are required: I, E
'''

As a user I do not know how to proceed. Pls update Macro read me, and automate the process of having an agent deployed in the cluster. 

Thanks

2023-04-17 18:09 UTC, vinayakSharm requested changes
Hi matt here are the steps I took to test your PR:

(1) I cloned your branch. 

(2) I then compiled the docker image locally from your branch

(3) pushed the docker image to dockerhub: teamrespons/respons_agent:matt.pr.test

(4) I then created a new manifest file: https://raw.githubusercontent.com/DISHDevEx/fonpr/vinny/action-handler-integration-pr/deployment/respons_agent_manifest.yml

(5) I deployed the agent to the EKS cluster

Here are my errors at step 5. The agent is deployed in the cluster but the logs say the following: 

'''
usage: FONPR_Agent [-h] I E
FONPR_Agent: error: the following arguments are required: I, E
'''

As a user I do not know how to proceed. Pls update Macro read me, and automate the process of having an agent deployed in the cluster. 

Thanks

2023-04-17 19:08 UTC, PaperArmada commented on fonpr/agent.py
> +    targets = [s for s in lim_reqs.keys() if 'amf' in s]
Done

2023-04-17 20:22 UTC, vinayakSharm requested changes
Hi matt, great work! 

Need logging from agent thanks

2023-04-17 20:23 UTC, PaperArmada commented on fonpr/agent.py
> +def loop_queries() -> None:
Done

2023-04-17 20:23 UTC, PaperArmada commented on fonpr/agent.py
> +    """
Done

2023-04-17 20:25 UTC, PaperArmada commented on fonpr/README.md
I'm inclined to leave it, at least for now. I want some breadcrumbs for people to be able to run it for themselves without having us directly involved.

2023-04-17 21:37 UTC, vinayakSharm commented
as discussed minor read me updates, and pr is approved. no code changes needed at this point looks solid. 

I would run pylint and black prior to pushing

2023-04-18 15:59 UTC, vinayakSharm approved these changes

2023-04-18 16:00 UTC, merged